apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argo-events
type: Opaque
data:
  token: ${ARGO_GITHUB_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: argo-events
  name: default.service-account-token
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
