apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: '{"token": "${GITHUB_TOKEN}", "username": "${GITHUB_USERNAME}"}'
---
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-github-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: github-creds
      key: credentials
