apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: example-public-repository
  namespace: crossplane-system
spec:
  forProvider:
    description: "This is a test repository for Crossplane"
    visibility: public
    template:
      - repository: "example_template"
        owner: "markopolo123"
  providerConfigRef:
    name: provider-github-config
